# Generated by Django 5.0.6 on 2024-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='default_value', max_length=255)),
                ('bot_response', models.TextField()),
            ],
        ),
    ]
