# Generated by Django 5.0.6 on 2024-07-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='default_value', max_length=255)),
                ('bot_response', models.TextField()),
            ],
        ),
    ]
