# Generated by Django 5.0.7 on 2024-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botresponse',
            name='bot_response',
            field=models.TextField(),
        ),
    ]
