import { Inter } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"

const inter = Inter({ subsets: ["latin"] });
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
      {children}</div></body>
    </html>
  );
}
