# Generated by Django 5.0.6 on 2024-07-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_forns_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forns',
            new_name='Forms',
        ),
    ]
