# Generated by Django 4.2.6 on 2024-11-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
